name: Create tbls documentation

on:
  push:
    branches:
      - main
    # paths:
    #   - "db/migrations/**"

jobs:
  doc:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h 127.0.0.1" --health-interval 20s --health-timeout 10s --health-retries 10

    steps:
      # チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # golang-migrateをインストール
      - name: Install golang-migrate CLI
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/migrate.list
          sudo apt-get update
          sudo apt-get install -y migrate

      - name: Wait for MySQL service
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h localhost -u root -ppassword; then
              echo "MySQL is up and running"
              break
            fi
            echo "Waiting for MySQL to be available..."
            sleep 2
          done

      - name: setup mysql
        run: |
          mysql -h localhost -u root -ppassword -e "CREATE DATABASE dbname"

      # データベースマイグレーションの実行
      - name: Run database migrations
        run: migrate -path db/migrations -database "mysql://root:password@tcp(localhost:3306)/dbname" up

      # tblsをセットアップ
      - uses: k1low/setup-tbls@v1

      # ドキュメントを生成
      - name: Run tbls to generate database documentation
        run: tbls doc mysql://root:password@tcp(localhost:3306)/dbname -o docs/tbls

      # 生成されたドキュメントをGitHub Pagesにデプロイ (オプション)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/tbls # 生成されたドキュメントのパス
