name: Create tbls documentation

on:
  push:
    branches:
      - main
    paths:
      - "db/migrations/**"

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # golang-migrateをインストール
      - name: Install golang-migrate CLI
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
          echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/migrate.list
          sudo apt-get update
          sudo apt-get install -y migrate

      # MySQLをセットアップ
      - name: Set up MySQL
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: dbname
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          sudo mysql -e "CREATE DATABASE IF NOT EXISTS dbname;"
          sudo mysql -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON dbname.* TO 'user'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      # データベースマイグレーションの実行
      - name: Run database migrations
        run: migrate -path db/migrations -database "mysql://user:password@tcp(localhost:3306)/dbname" up

      # tblsをセットアップ
      - uses: k1low/setup-tbls@v1

      # ドキュメントを生成
      - name: Run tbls to generate database documentation
        run: tbls doc mysql://user:password@tcp(localhost:3306)/dbname -o docs/tbls

      # 生成されたドキュメントをGitHub Pagesにデプロイ (オプション)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/tbls # 生成されたドキュメントのパス
